version: "3.9"

services:
  db:
    ports:
      - "5432:5432"

  tailwind:
    build:
      context: ./tailwind
      dockerfile: Dockerfile
    tty: true
    restart: always
    volumes:
      - ./tailwind:/src
      - ./assets:/dst
      - ./templates:/templates